#!/usr/bin/env bash
# Install and start nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World" | sudo tee -a /var/www/html/index.html
