#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee -a /var/www/html/index.html
sudo sed -i "46i rewrite ^/redirect_me https://www.eltiempo.com permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
