#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get install -y --allow-downgrades nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee -a /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
#put in line 46 of default page
sudo sed -i "47i\ \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n \
\\terror_page 404 /custom_404.html;\n" /etc/nginx/sites-available/default
sudo service nginx restart
