#!/usr/bin/env bash
# use echo to print the msg
hrs=0
while [ $hrs -le 12 ]
do
	echo "Hour: $hrs"
    	min=1
    	while [ $min -lt 60 ]
    	do
		echo "$min"
		((min++))
    	done
    	((hrs++))
done
